---
apiVersion: v1
kind: Namespace
metadata:
  name: "qrgen"
...
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: qrgenerator-quota
  namespace: "qrgen"
spec:
  hard:
    requests.cpu: "1200m"
    requests.memory: 512Mi
    limits.cpu: "1200m"
    limits.memory: 512Mi
...
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-conf
  namespace: "qrgen"
data:
  telegraf.conf: |
    [global_tags]
      project = "qrgenerator"
    [agent]
      interval = "30s"
      logtarget = "stderr"
      omit_hostname = false
    [[inputs.nginx]]
      urls = ["http://localhost:8000/basic_status"]
      response_timeout = "5s"
    [[outputs.prometheus_client]]
      listen = ":9273"
      metric_version = 2
      path = "/metrics"
      expiration_interval = "120s"
      collectors_exclude = ["gocollector", "process"]
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrgenerator-front
  namespace: "qrgen"
  labels:
    app.kubernetes.io/name: qrgenerator-front
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: qrgenerator-front
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qrgenerator-front
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9273"
    spec:
      containers:
        - name: front-nginx
          imagePullPolicy: Always
          image: "registry.againddm.keenetic.pro/homelab/qr-front:latest"
          resources:
            limits:
              cpu: "250m"
              memory: "64Mi"
            requests:
              cpu: "250m"
              memory: "64Mi"
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 101
            runAsGroup: 101
          ports:
            - name: frontend-port
              containerPort: 8080
            - name: service-port
              containerPort: 8000
          startupProbe:
            httpGet:
              path: /ping
              port: service-port
            failureThreshold: 30
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /ping
              port: service-port
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: frontend-port
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 3
            failureThreshold: 3
          volumeMounts:
            - mountPath: /tmp
              name: nginx-tmp
          terminationMessagePolicy: FallbackToLogsOnError
        - name: telegraf-sidecar
          imagePullPolicy: Always
          image: "telegraf:1.22"
          command:
            - "telegraf"
          args:
            - "--config"
            - "/etc/telegraf/telegraf.conf"
          resources:
            limits:
              cpu: "50m"
              memory: "64Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 999
            runAsGroup: 999
          ports:
            - name: metrics-port
              containerPort: 9273
          startupProbe:
            httpGet:
              path: /metrics
              port: metrics-port
            failureThreshold: 30
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics-port
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics-port
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 2
            failureThreshold: 3
          volumeMounts:
            - mountPath: /etc/telegraf
              name: telegraf-conf
          terminationMessagePolicy: FallbackToLogsOnError
      volumes:
        - name: nginx-tmp
          emptyDir:
            sizeLimit: 64Mi
        - name: telegraf-conf
          configMap:
            name: telegraf-conf
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - qrgenerator-front
                topologyKey: kubernetes.io/hostname
...
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qrgenerator-front-hpa
  namespace: "qrgen"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qrgenerator-front
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
...
---
kind: Service
apiVersion: v1
metadata:
  name: qrgenerator-front
  namespace: "qrgen"
  labels:
    app.kubernetes.io/name: qrgenerator-service-front
  annotations:
    traefik.ingress.kubernetes.io/service.passhostheader: "true"
spec:
  ports:
    - name: frontend-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: qrgenerator-front
...
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: qrgenerator
  namespace: "qrgen"
  labels:
    app.kubernetes.io/name: qrgenerator-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: qr.againddm.keenetic.pro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qrgenerator-front
                port:
                  number: 8080
  defaultBackend:
    service:
      name: qrgenerator-front
      port:
        number: 8080
...
